import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[font]
size = 15

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

[window]
padding = { x = 15, y = 15 }
